:::{.chapter}
# Chapter Three
## Where we are going to present all the feature
:::

You can use *italics*, **bold**, ***bold italics***, superscript^2^, subscript~2~, ~~strikethrough~~, `verbatim inline code`, Angle brackets links <https://quarto.org>, Classic markdown links [Quarto](https://quarto.org).

{{< scenebreak line >}}

You can also have footnote reference,[^1] and another.[^longnote]. Here is an inline note.^[Inlines notes are easier to write,
since you don't have to pick an identifier and move down to
type the note.]

[^1]: Here is the footnote.

[^longnote]: Here's one with multiple blocks.

    Subsequent paragraphs are indented to show that they
belong to the previous footnote.

    The whole paragraph can be indented, or just the first
    line.  In this way, multi-paragraph footnotes work like
    multi-paragraph list items.

This paragraph won't be part of the note, because it
isn't indented.

{{< scenebreak line >}}

And also some shortcodes:

For example the `lipsum` shortcode separated by `scenebreak` shortcodes of different types:

{{< lipsum 1 >}}

{{< scenebreak >}}

{{< lipsum 1 >}}

{{< scenebreak blank >}}

{{< lipsum 1 >}}

{{< scenebreak line >}}

{{< lipsum 1 >}}

{{< scenebreak stars >}}

{{< lipsum 1 >}}

Now we jump 5 lines with `emptylines` shortcode

{{< emptylines 5 >}}

Jumped!

You can use an epigraph with an `epigraph` div:

:::{.epigraph by="John Lennon" from="An interview"}
When I was 5 years old, my mother always told me that happiness was the key
to life. When I went to school, they asked me what I wanted to be when I
grew up. I wrote down ‘happy’. They told me I didn’t understand the
assignment, and I told them they didn’t understand life.
:::

You can even use an epigraph with multiple paragraphs:

:::{.epigraph by="John Lennon" from="An interview"}
When I was 5 years old, my mother always told me that happiness was the key
to life. When I went to school, they asked me what I wanted to be when I
grew up. I wrote down ‘happy’. They told me I didn’t understand the
assignment, and I told them they didn’t understand life.

When I was 5 years old, my mother always told me that happiness was the key
to life. When I went to school, they asked me what I wanted to be when I
grew up. I wrote down ‘happy’. They told me I didn’t understand the
assignment, and I told them they didn’t understand life.
:::

...or with line block:

:::{.epigraph by="Robert Frost" from="Nothing Gold Can Stay"}
| Nature's first green is gold,
| Her hardest hue to hold.
| Her early leaf's a flower;
| But only so an hour.
:::

It's also possible to ask for a new page with the `clearpage` shortcode:

{{< clearpage >}}

This should appear on a new page.

And you can even ask for for a new page  that force the next page to be recto with the `cleartorecto` shortcode:

{{< cleartorecto >}}

This should appear on a new recto page.

And you can also simply put an empty page using `emptypage` and `clearpage` shortcode:

{{< clearpage >}}
{{< emptypage >}}
{{< clearpage >}}

And here is the followup after an empty page.

Now let's try to format multiple paragraps at once using a div with formating attributes:

:::{.bold}
{{< lipsum 2 >}}
:::

:::{.italic}
{{< lipsum 2 >}}
:::

:::{.strikethrough}
{{< lipsum 2 >}}
:::

:::{.bold .italic}
{{< lipsum 2 >}}
:::

And the same thing with spans [this is bold]{.bold}, [this is italic]{.italic}, [this is strikethrough]{.strikethrough} and [this is both]{.bold .italic}, that's it.