:::{.chapter}
## Chapter 4: DIVs {lines_before=1}
### Test of many combinations of formating classes {lines_before=5}
:::

### 1. Simple div

:::{}
Fugiat aute incididunt magna qui irure, non ullamco culpa nisi enim. Sit mollit
qui sint. Eu cupidatat enim aliqua enim. Culpa quis ea voluptate magna nulla,
irure tempor elit lorem. Eiusmod lorem nisi fugiat commodo eiusmod. Fugiat quis
lorem ex. Dolor enim reprehenderit elit aute enim. Ipsum aliquip et tempor. Ad
labore mollit fugiat eu, in magna sit eiusmod duis, esse aliquip sint aliqua
tempor veniam adipiscing eu. Anim commodo sint irure laborum lorem cillum,
laboris nulla non exercitation pariatur occaecat commodo aute.

Anim adipiscing elit pariatur consequat qui. Ut exercitation nisi nisi ut dolor,
aliquip ad fugiat voluptate cupidatat eu, laborum ea culpa tempor sed cupidatat
consectetur deserunt. Pariatur velit pariatur minim ipsum nostrud. Sed do do
aliquip adipiscing eu dolore cupidatat. Dolore qui qui deserunt id ad.
Cupidatat proident deserunt tempor aute, minim nostrud nisi occaecat lorem sint
cupidatat. Nisi tempor cillum consequat excepteur aliqua nostrud consequat.
Nisi non aliqua eu consequat voluptate. Magna labore culpa eiusmod ex amet
nostrud dolore. Commodo excepteur ea ullamco adipiscing adipiscing culpa
commodo, ex nisi nulla proident est.

Tempor irure commodo proident adipiscing. Do enim et sed, qui in consequat
labore ipsum sunt amet officia. Ex aute anim quis. Voluptate amet magna non
fugiat consequat velit sunt. Aute proident eu fugiat ut consequat non proident.
Cupidatat irure esse irure eu elit exercitation aute.
:::

### 2. Bold div

Two next paragraphs are formated as bold.

:::{.bold}
Deserunt duis ad consequat aliquip nostrud reprehenderit velit. Ipsum amet in
enim minim ullamco amet tempor, tempor consectetur ut occaecat incididunt sint,
anim elit sint ipsum dolor. Nisi ea non voluptate aute velit elit enim, magna
magna ad aute aliqua ut cupidatat quis. Ullamco esse proident commodo eu,
dolore ullamco est aliquip enim voluptate ut eu, est enim labore enim do esse
dolore. Sed ad aute fugiat lorem eiusmod sint ex. Nulla consequat consectetur
culpa elit cupidatat commodo. Cillum irure do ad mollit ullamco ut laboris.
Commodo sunt laboris cupidatat voluptate dolor, aliquip cupidatat commodo dolor
magna. Nostrud nulla cupidatat qui sint culpa.

Officia fugiat sunt qui. Incididunt incididunt proident et elit ut, commodo
mollit ullamco culpa esse, eu labore sint mollit labore quis deserunt sed.
Nulla aliquip reprehenderit pariatur dolore id labore dolor, commodo sunt
laboris ex minim aliquip. Adipiscing laboris pariatur voluptate excepteur
cillum. Velit labore et minim mollit lorem. Ea ullamco minim sed qui
reprehenderit. Quis tempor et nisi in.
:::

### 3. Italic div {line=false}

Two next paragraphs are formated as italic.

:::{.italic}
Ullamco ad nisi deserunt. Dolor nisi ut occaecat officia proident proident, ut
adipiscing qui eu dolor irure. Excepteur aliquip aliqua ipsum proident. Culpa
laborum laboris nisi nostrud. Sunt officia amet non.

Ea nostrud ipsum sit. Dolore est dolore consectetur. Laboris occaecat adipiscing
culpa. Est in officia non quis mollit. Do qui laborum consequat laboris
incididunt. Amet velit sint do, aute commodo nulla nostrud voluptate. Deserunt
deserunt nisi sed exercitation elit ipsum. Reprehenderit tempor ea velit enim,
in ex esse tempor cupidatat consequat.
:::

### 4. Strikethrough div {line=true}

Two next paragraphs are formated as strikethrough.

:::{.strikethrough}
Culpa occaecat aliquip culpa enim nostrud veniam, esse sit aliquip eu sint duis,
eiusmod ex minim ea voluptate in cupidatat. Commodo eu eu ipsum ex ut, elit
occaecat commodo non adipiscing labore officia esse. Ullamco laboris sunt dolor
nulla mollit sint. Sunt sunt incididunt consequat ut sunt. Culpa culpa velit
commodo non aliqua ex ea. Sint officia enim mollit sit excepteur voluptate.
Incididunt ipsum ea et lorem, mollit anim laborum nisi nisi.

Proident sint id sit do quis, adipiscing sint officia laborum. Dolor do nostrud
laborum. Esse consequat sint esse dolore, et sint adipiscing laboris nostrud et
nostrud lorem. Ea incididunt id voluptate occaecat. Mollit aute cupidatat do
incididunt est, sunt velit proident sint, aliqua dolore occaecat elit lorem
pariatur veniam. Fugiat incididunt aute qui.
:::

### 5. Small capitals div

Two next paragraphs are formated in small caps.

:::{.smallcaps}
Labore pariatur ex incididunt exercitation reprehenderit. Minim nisi adipiscing
nulla non qui. Duis ullamco sit incididunt lorem aute. Quis mollit in dolore
adipiscing elit cupidatat. Consequat ullamco cupidatat tempor et. Consequat
minim aliquip dolor ullamco minim.

Sint voluptate cupidatat officia velit ex. Lorem nisi occaecat nostrud et minim
sed ea. Cillum enim occaecat eu ex, reprehenderit anim mollit eiusmod elit. Qui
ex lorem consectetur laborum officia proident. Aliquip dolor sunt consectetur
ipsum mollit. Do veniam aliqua veniam duis nostrud anim. Duis dolor et anim.
Veniam dolor velit consequat cillum commodo anim.
:::

### 6. Monospaced div

Five next paragraphs are formated in monospace (aka teletext) font.

:::{.monospace}
Unlike verbatim, you can use **bold text**, *italic text* and ***bold italic
text*** in the monospace divs or spans just like in any other place.

You can split a very log string so that it fits in the page via hyphenation by
inserting a `\-` where you want the string to be cut and wrapped. Here is an
example:

1111111111222222222233333333334444444444555555555566666\-6666677777777778888888888

Ad dolor enim nulla, nisi sint magna velit commodo nisi elit amet. Commodo
proident in pariatur officia anim. Et cillum cupidatat est excepteur sed,
adipiscing aliquip proident adipiscing excepteur duis est ipsum. Esse fugiat
pariatur adipiscing qui anim consectetur deserunt. Ullamco velit ipsum duis
incididunt. Cillum deserunt pariatur officia aliquip ut. Elit quis magna ad.
Eiusmod ipsum exercitation incididunt dolor anim ex, nisi veniam eu enim
proident ea ex, incididunt nostrud dolore voluptate. Deserunt proident ullamco
adipiscing exercitation irure ea labore. Elit do nulla enim do veniam
excepteur.

Esse mollit ipsum sunt proident dolor tempor, ad lorem laborum pariatur.
Voluptate voluptate laboris sunt eiusmod consectetur occaecat. Pariatur est
esse commodo adipiscing nulla. Aliquip magna culpa ex reprehenderit nisi culpa,
mollit sint id consequat elit minim. Sit sunt minim id consequat. Fugiat
exercitation incididunt in consectetur veniam dolore nulla.
:::

### 7. Sans serif div

Three next paragraphs are formated in sans serif font.

:::{.sans}
You can use **bold text**, *italic text* and ***bold italic text*** in the sans
divs or spans just like in any other place.

Eiusmod nisi et nostrud occaecat amet, officia nostrud pariatur enim voluptate
irure, ipsum sunt culpa eu aute consectetur duis pariatur. Nulla magna
incididunt et commodo sed. Deserunt eiusmod aute ex. Consequat culpa mollit
magna duis dolor aliquip. Sint laboris irure dolor.

Proident anim mollit aute laborum ea incididunt, sint nostrud quis elit
adipiscing aliqua ut duis, in anim amet nisi magna tempor eu excepteur. Lorem
ad eu id culpa. Dolor ut laboris et commodo, id dolore sed anim ad, qui duis eu
consectetur laboris occaecat minim commodo. Occaecat aliquip pariatur ad
officia incididunt ipsum velit. Do fugiat nostrud minim veniam ipsum amet
proident, ullamco irure labore eu proident consequat consectetur ullamco.
Deserunt ea nostrud quis, aute et culpa nulla irure magna. Voluptate irure
lorem proident minim ipsum dolore amet.
:::

### 8. Combined classes div

Two next paragraphs are formated with combinations of previous formating
classes.

:::{.bold .italic .strikethrough .smallcaps}

Veniam aute proident consectetur culpa enim, pariatur exercitation reprehenderit
dolor ut mollit quis. Veniam velit non reprehenderit occaecat. Voluptate minim
aliqua amet tempor laboris cillum, voluptate esse ut cillum exercitation.
Pariatur eu occaecat officia laboris lorem labore nostrud, cillum minim
incididunt veniam do sint. Dolor excepteur veniam cillum. Mollit pariatur elit
ut amet duis eiusmod nulla. Commodo ex occaecat laboris sunt sed sed cillum,
qui cupidatat consequat dolor dolor. Labore sunt quis pariatur. Ex labore do
deserunt, adipiscing non est duis aliqua do, deserunt sint pariatur sit
adipiscing pariatur. Do tempor aute cupidatat pariatur.

Cillum sed anim ex excepteur velit ullamco. Elit dolore fugiat lorem commodo.
Aliqua exercitation reprehenderit eu anim eu non magna. Quis deserunt aliquip
veniam lorem culpa, ad fugiat laboris eiusmod voluptate aliquip cillum culpa.
Aliquip laboris cupidatat adipiscing. Eiusmod lorem qui enim reprehenderit
voluptate sunt et. Do magna cillum ad adipiscing veniam in voluptate, in amet
in duis eu, laborum ut cupidatat anim velit ea reprehenderit. Esse enim magna
cupidatat, incididunt consequat non cupidatat sed officia laborum, ea do
adipiscing exercitation incididunt fugiat cupidatat.
:::

### 9. Div without paragraph indentation

Two next paragraphs have no paragraph indentation.

:::{.noparindent}
Excepteur amet adipiscing aliquip aliqua nostrud. Aliqua sint officia
reprehenderit consequat in. Nisi lorem est in. Fugiat amet magna cupidatat
exercitation veniam velit incididunt. Aute dolore velit occaecat elit laboris.
Pariatur consectetur est sunt ea, ut culpa veniam tempor laborum, eiusmod sunt
elit veniam aliqua sit. Anim eu excepteur exercitation sit excepteur. Enim ut
duis occaecat id sint elit in. Officia consectetur et mollit nostrud fugiat
non. Culpa velit reprehenderit velit, elit commodo incididunt laborum ea
velit.

Occaecat ex ad consequat sint enim sit. Fugiat quis magna deserunt voluptate
sit. Officia anim dolore culpa dolore. Qui culpa non reprehenderit et
reprehenderit. Cillum laborum et id et aliquip reprehenderit commodo. Aliquip
minim reprehenderit esse consequat culpa.
:::

### 10. Div with space between paragraphs

Three next paragraphs space between them.

:::{parskip=1ex}
Dolore sunt non ut laboris lorem et, voluptate do non et consectetur deserunt.
Esse aliquip cillum incididunt incididunt occaecat sunt. Amet voluptate
consectetur cillum do sit, aliquip fugiat irure nostrud laborum laboris elit
ipsum. Mollit non culpa amet. Do sed tempor ipsum ullamco velit adipiscing
esse. Eu sit eiusmod reprehenderit excepteur.

Anim sunt consectetur reprehenderit nisi enim esse adipiscing, enim proident
aliquip in sed eiusmod occaecat reprehenderit. Velit dolore consequat dolore
quis qui, veniam eu amet nisi, non eiusmod ea cupidatat nostrud velit officia
ex. Voluptate mollit commodo cupidatat lorem cupidatat esse qui, nisi proident
exercitation quis nisi excepteur quis culpa, aute mollit in qui amet laborum.
Irure nisi amet aute elit labore magna. Ad irure et occaecat pariatur veniam
culpa sit. Dolor reprehenderit consequat sit minim labore quis reprehenderit.
Velit laboris nisi enim amet irure, labore lorem est nulla anim laborum nisi
ullamco. Pariatur velit fugiat reprehenderit aliquip commodo ut nisi. Occaecat
deserunt irure quis laborum adipiscing minim tempor, adipiscing non cillum
labore et. Incididunt do laboris ipsum pariatur incididunt ut adipiscing, et eu
voluptate velit reprehenderit pariatur culpa est, incididunt officia officia
nisi.

Nulla sunt culpa do ipsum. Lorem nisi ea nulla. Dolore pariatur aliquip veniam
nulla lorem velit, cupidatat velit dolor irure ad nulla ex eu. Ipsum ut ea sint
sed duis culpa. Officia voluptate qui ex. Sit nostrud ex magna incididunt
fugiat duis est, commodo labore reprehenderit sunt.
:::

And some text after the last paragraph (there should be space before it).

{{< clearpage >}}

### 11. Vertival spaces

Next paragraph has filling space before and after and so should be vertically
centered.

:::{vfill=both}
Sunt ad labore quis ea ad aliquip, ad laborum reprehenderit et mollit sed quis.
Ullamco cillum sit ipsum. Ad eu nostrud nostrud consectetur sunt esse sunt,
exercitation consectetur sed nulla ullamco sint laborum. Cupidatat aliquip
minim minim nulla consectetur commodo aute. Sit reprehenderit sed et. Proident
officia cupidatat id duis magna. Ad eu consequat irure irure. In pariatur eu
non aliqua laboris ut.
:::

Some text down the page.

{{< clearpage >}}

Next paragraph has filling space before only and so should be pushed down the
page.

:::{vfill=before}
Proident exercitation ipsum id minim magna proident nostrud. Esse in enim lorem
occaecat, laboris cupidatat aliquip officia ea. Veniam nostrud nulla
exercitation labore qui duis ullamco. Ad ipsum aliquip velit nulla dolore. Est
nulla adipiscing sint qui ullamco elit aliquip. Amet ea sunt mollit, sint
aliqua id voluptate proident nostrud est. Consectetur nisi enim laborum fugiat
tempor occaecat et, nisi in sunt quis, occaecat exercitation non lorem labore
in et nisi. Fugiat tempor dolore quis velit officia. Sed qui ullamco minim nisi
officia amet.
:::

Some text down the page.

{{< clearpage >}}

Next paragraph has filling space after only and so following content should be
pushed down the page.

:::{vfill=after}
Adipiscing ea ipsum sit labore. Veniam cillum lorem velit officia. Minim dolore
officia ut commodo incididunt sed consectetur, labore id sint sint duis.
Laboris cillum qui sed deserunt aliquip consectetur ea. Irure amet dolore aute
commodo voluptate anim ut, reprehenderit excepteur labore consequat excepteur.
Irure consequat dolore nostrud voluptate, id tempor ad fugiat. Eu culpa qui
sed.
:::

Some text down the page.

{{< clearpage >}}

Next div has vertical space before and after.

:::{vspace_both=3\nbs}
Nulla culpa excepteur do pariatur, laborum nisi mollit cillum officia velit
incididunt eiusmod. Cillum sit do occaecat et. Fugiat laboris esse qui eu
pariatur. Nisi non voluptate laboris pariatur occaecat occaecat deserunt. Nulla
proident deserunt duis nostrud. Dolor laboris culpa voluptate pariatur duis
non, ullamco non veniam eu aliqua anim ullamco velit. Consequat proident dolore
nulla duis aute sunt, duis sunt adipiscing ullamco fugiat sed ad. Aliqua
reprehenderit aliqua pariatur in adipiscing sed nulla, culpa et nisi sunt
proident minim.

Veniam ea dolor consectetur aliqua sed, non aliqua enim amet magna ullamco.
Labore non aute laboris aliqua qui. Ipsum amet sunt reprehenderit do occaecat.
Id et velit elit voluptate quis quis ex, officia nulla qui elit qui commodo
ipsum. Aliqua eu aliqua labore adipiscing, nostrud sed nisi officia. Lorem
laboris sit commodo, ipsum aliquip veniam elit cillum, proident aute adipiscing
ex do. Sint labore reprehenderit cupidatat nisi occaecat. Aliquip ea aliquip
laboris mollit amet cillum.
:::

Next div has vertical space before.

:::{vspace_before=3\nbs}

Nulla irure tempor ullamco dolor dolor. Anim sed amet incididunt lorem. Velit
sint eu magna veniam lorem. Reprehenderit sed minim velit sint cillum eiusmod.
Amet quis pariatur do fugiat nostrud sint aute, fugiat mollit mollit amet sit
sit voluptate incididunt. Aute incididunt aliqua aute. Sunt incididunt aute
consectetur ea laborum in. Aliquip non proident voluptate incididunt.

Eu consequat nostrud eiusmod do eiusmod incididunt, eu laboris consectetur
nostrud aute excepteur, est tempor in duis. Occaecat veniam excepteur culpa qui
nostrud sunt ullamco. Dolore pariatur commodo sunt incididunt pariatur tempor
consequat. Quis proident consectetur eu dolor ad nostrud. Exercitation
incididunt id excepteur. Nulla adipiscing veniam eiusmod anim labore cillum.
:::

Next div has vertical space after.

:::{vspace_after=3\nbs}
Dolor nostrud deserunt reprehenderit consequat. Sunt nulla exercitation aliquip
enim. Officia reprehenderit in ea tempor nostrud laborum. Lorem tempor magna
sit enim mollit minim ut, do adipiscing eu lorem. Dolore reprehenderit et nisi
magna eiusmod, adipiscing pariatur nisi dolor laborum dolore.

Et ipsum proident proident. Aliqua sed proident ad minim veniam anim aliquip.
Aliquip id culpa ipsum sed. Incididunt exercitation ad nisi aliqua
reprehenderit et. Dolor mollit nisi commodo anim est. Aliqua tempor sint
proident. Ullamco mollit labore cillum velit eiusmod. Est ad non et non. Esse
commodo voluptate magna aliquip minim consequat. Consectetur non ut laboris
consectetur.
:::

Next div has vertical space before and after (using shortcut in number of
lines).

:::{lines_both=3}
Cillum anim nulla officia. Tempor eiusmod ipsum consequat, aliqua exercitation
laboris nulla enim officia aliqua amet. Consequat deserunt laboris do voluptate
qui. Fugiat duis reprehenderit eu cupidatat sit velit, incididunt eiusmod ipsum
est labore labore laboris, consequat nulla incididunt qui laboris enim quis
laborum. Fugiat tempor cupidatat nostrud magna, reprehenderit consectetur ipsum
consequat laborum ullamco lorem. Lorem exercitation elit cupidatat. Dolore ad
eiusmod mollit consequat, ea minim sed cillum culpa qui aliquip aliqua.

Esse dolor adipiscing tempor cupidatat ullamco mollit enim, cillum ipsum
voluptate magna do velit nulla ad. Veniam sint pariatur velit voluptate eiusmod
ea, culpa et lorem incididunt reprehenderit. Aute duis et ad est. Minim ullamco
deserunt enim nisi laborum magna, esse sunt duis excepteur et, consequat irure
sunt occaecat excepteur amet incididunt sunt. Officia id occaecat occaecat, qui
dolor proident adipiscing. Aliquip ut officia aute labore veniam duis laboris.
Elit lorem sed proident dolore lorem.
:::

Next div has vertical space before (using shortcut in number of lines).

:::{lines_before=3}
Sed nisi irure anim esse do proident. Officia labore commodo officia irure esse
enim, dolor officia pariatur adipiscing et tempor laboris est, enim
exercitation et proident deserunt cillum laborum ut. Veniam irure consequat
laboris aliquip excepteur ad, veniam ad nisi nulla, pariatur consequat
consectetur lorem consectetur sed ad tempor. Do culpa occaecat enim. Duis eu
nulla dolor. Aliqua non consequat qui est sint proident ipsum, mollit sunt
reprehenderit elit dolore. Quis ea sit velit, ut irure mollit ipsum id labore
irure ullamco. Aliqua aliqua do consectetur, consectetur tempor excepteur non,
mollit fugiat minim consequat sed. Esse labore eu veniam in laborum ipsum, sit
est sint sit esse non minim aliquip.

Sit do exercitation qui sit est dolore exercitation. Do do elit ut labore et. Eu
nostrud velit qui aute cillum veniam nisi. Voluptate labore quis adipiscing. Ea
sed velit dolore incididunt consequat do commodo, veniam sint fugiat
reprehenderit.
:::

Next div has vertical space after (using shortcut in number of lines).

:::{lines_after=3}
Fugiat pariatur laborum cillum ad. Exercitation deserunt non sit lorem. Sunt
dolor excepteur incididunt consectetur, occaecat irure laborum aliquip ex
laboris. Voluptate duis est dolor magna fugiat velit. Dolore anim cillum sunt
sit ipsum, reprehenderit amet enim ipsum commodo.

Deserunt nulla sint esse exercitation. Eiusmod excepteur exercitation occaecat
duis non culpa, aliquip ipsum laboris proident sunt sit. Dolor ea ipsum nostrud
consectetur occaecat. Sint est nisi culpa nostrud officia duis. Eiusmod do
consequat fugiat ut reprehenderit, minim voluptate lorem commodo tempor
excepteur excepteur nulla. Do ex lorem pariatur cupidatat pariatur amet,
pariatur elit laboris mollit excepteur sed. Ullamco veniam nisi qui anim sed.
:::

Some text after.

### 12. Margins

Next divs have different left margins.

:::{margin_left=1em}
Laborum in eiusmod aliqua ut, dolore consequat mollit ex non laborum eiusmod.
Anim ullamco sint irure lorem dolore, labore consectetur sunt proident. Duis
culpa aute ullamco qui. Reprehenderit culpa irure sint ut deserunt aute. Dolore
proident esse velit nostrud sunt consequat, enim veniam tempor laborum. Cillum
exercitation reprehenderit nulla pariatur dolore.
:::

:::{margin_left=3em}
Cupidatat amet ipsum consectetur tempor commodo ea cillum. Culpa reprehenderit
ad occaecat quis enim cillum. Veniam qui ea et sunt do incididunt ut, voluptate
est cupidatat laboris sed laboris sint. Sit aute do et, dolore aliquip dolore
lorem ex esse magna ut. Lorem velit officia duis. Consectetur quis officia
sunt. Aute culpa est eu incididunt, proident incididunt occaecat duis magna sed
anim duis, quis magna nostrud laboris. Qui reprehenderit in duis occaecat
proident. Magna tempor ullamco deserunt reprehenderit labore ullamco.
:::

:::{margin_left=5em}
Voluptate cupidatat in sint anim ut velit, laborum nulla amet esse
reprehenderit. Ullamco culpa dolore adipiscing laboris. Deserunt commodo dolor
labore consequat. Pariatur deserunt sed eu. Id sed deserunt ullamco duis. Est
non fugiat quis dolore nisi eiusmod. Nulla est labore deserunt. Dolor aliquip
ad eiusmod nostrud in sed nisi. Sint proident amet tempor nulla aute.
:::

Next divs have different right margins.

:::{margin_right=1em}
Sed lorem elit deserunt excepteur nulla. Irure do ut nulla duis reprehenderit ex
irure, anim lorem consectetur excepteur voluptate officia. Non sunt pariatur
et. Magna excepteur ex deserunt exercitation magna in sed. Id laboris quis est
ut consectetur anim fugiat, eu proident voluptate non nisi.
:::

:::{margin_right=3em}
Mollit tempor cupidatat amet dolor magna irure cupidatat, labore adipiscing anim
sit ipsum reprehenderit ullamco aliquip, sunt pariatur eiusmod incididunt
proident ut mollit. Magna excepteur deserunt sint proident. Ullamco incididunt
ullamco officia. Deserunt magna nisi sit exercitation ipsum. Do pariatur
laboris est, incididunt reprehenderit sunt sint esse. Deserunt laboris in
occaecat. Cillum ad non ipsum sunt, non pariatur est nostrud excepteur. Dolore
veniam occaecat est ad fugiat exercitation laborum, ea fugiat nostrud nulla
tempor tempor, velit eu est sunt fugiat excepteur. Amet sed proident culpa
magna.
:::

:::{margin_right=5em}
Cupidatat magna laborum cupidatat. Ullamco excepteur eu amet esse reprehenderit
amet pariatur. Non culpa velit non dolore nisi ullamco. Et laboris quis nisi
laboris. Consectetur aute lorem pariatur fugiat officia. Lorem consequat
reprehenderit lorem reprehenderit, ex minim lorem enim anim enim exercitation
ex, veniam proident incididunt magna fugiat occaecat. Sed laboris nostrud
laborum, aliqua id magna et dolor labore cillum, cupidatat consectetur duis
aliquip. Deserunt laborum laborum ad ex incididunt, commodo sed duis do enim
minim.
:::

Next divs have different right and left margins.

:::{margin_both=1em}
Ad non ullamco pariatur laborum qui. Do duis sed do cillum nostrud. Voluptate
adipiscing enim nisi pariatur ex cillum. Sit eu eiusmod sed deserunt ut aliqua.
Dolor irure reprehenderit incididunt aliquip. Ea aute enim do officia proident
officia laboris, dolor quis fugiat aute qui consectetur, voluptate occaecat ea
aute ea eiusmod aliqua. Voluptate laboris pariatur ullamco voluptate est
reprehenderit. Ea anim est exercitation esse id lorem eiusmod. Fugiat eu esse
nulla culpa labore do aliqua, enim quis nisi mollit excepteur commodo esse,
incididunt non cillum ea minim anim commodo.
:::

:::{margin_both=3em}
Officia sed sed voluptate eu. Eu aliqua quis mollit dolore. Laborum esse quis
aute, ut ex veniam dolor aute officia. Irure eu sint reprehenderit esse commodo
adipiscing id. Velit sit quis sed proident.
:::

:::{margin_both=5em}
Magna nisi proident magna voluptate, voluptate ipsum proident occaecat laborum
aute. Commodo laborum minim sint elit in. Anim incididunt duis aliquip, tempor
tempor magna nulla non pariatur, est dolor laboris sed. Duis sed esse cillum
proident. Irure aliqua ex cillum laborum adipiscing ullamco. Duis consequat qui
eiusmod non dolore est adipiscing. Dolor proident officia ipsum. Non nulla
aliqua velit eiusmod, eiusmod cupidatat fugiat ex reprehenderit occaecat.
:::

### 13. Margins

Next divs have different left alignment.

:::{align=left}
Sunt nisi consectetur officia aute incididunt, consectetur veniam commodo
laborum aute deserunt, ea minim quis est culpa excepteur minim proident. Aliqua
consectetur do officia cillum consequat. Lorem adipiscing fugiat aute magna
aliqua. Voluptate nostrud pariatur anim consectetur id laborum velit, sunt
aliquip consectetur tempor. Quis laboris amet veniam non adipiscing, lorem
aliquip labore ad. Velit ad non qui occaecat est. Exercitation dolore veniam eu
ex sint.
:::

:::{align=right}
Proident labore sint nisi duis. Velit ea incididunt consequat adipiscing, quis
et pariatur nulla nostrud laboris cillum dolore. Aliqua sed commodo culpa sint
cupidatat. Officia laborum nostrud ea consequat ullamco. Quis ipsum sunt sit
dolore et culpa. Ipsum incididunt enim magna voluptate aute. Ut fugiat anim
ullamco eu sint tempor, aliqua nostrud aute duis in cupidatat.
:::

:::{align=center}
Amet nulla veniam aute magna non, eiusmod consequat et magna esse aliquip
officia. Sit culpa laborum qui. Consequat deserunt fugiat sunt do deserunt
quis, lorem exercitation cupidatat non reprehenderit, sint do ex labore. Veniam
magna anim officia lorem cillum aliquip, dolore amet nostrud officia laboris
elit, consectetur culpa sunt sit pariatur. Laborum quis elit aute laborum.
Labore qui magna sed eiusmod incididunt ad non. Aliquip nostrud quis anim ut
ex, consectetur laboris nostrud nisi.
:::

:::{align=justify}
Nulla amet aliqua fugiat. Est non id aliqua adipiscing sint in et. Enim
consequat commodo eiusmod nostrud. Consequat fugiat dolore enim dolor non do
magna, eu consequat sed ex, in eiusmod aliquip do. Anim quis fugiat pariatur
sed consequat in ad, mollit ea amet occaecat aute, commodo eiusmod enim sunt
tempor eu veniam cupidatat.
:::

And you can nest them:

:::{align=left}
Aute tempor aliqua elit sit proident deserunt, ea in officia nulla ad sint.
Veniam ut amet sed id excepteur ea incididunt, duis fugiat adipiscing proident.
Elit sint veniam non elit. Eu veniam tempor ipsum est sed proident. Eu ex minim
velit. Incididunt culpa elit excepteur ut minim lorem, duis nulla id commodo,
excepteur dolore ut in amet nostrud proident sed. Eiusmod reprehenderit aute
deserunt ut.

::::::{align=justify}
In magna ullamco id non fugiat ut laboris. Sed aute cillum cupidatat, consequat
consectetur laboris tempor aute. Adipiscing ad ut occaecat ad exercitation.
Anim sit irure mollit reprehenderit. Voluptate occaecat minim eu in proident
duis. Duis esse do enim quis veniam cupidatat. Ipsum magna eu commodo et
aliquip. Do cupidatat laboris anim. Reprehenderit magna eiusmod exercitation
commodo exercitation, minim ullamco anim reprehenderit irure, ex nulla sed
cillum excepteur.
::::::

Consectetur proident nulla anim labore qui. Dolor irure culpa dolor ea cupidatat
sit. Reprehenderit pariatur veniam ut, mollit voluptate labore ut adipiscing
labore aliquip. Dolor quis est anim, id dolor ad eiusmod dolor sed anim. Nulla
sunt aute exercitation deserunt do qui do, tempor incididunt amet sit. Elit
aliqua lorem non et.
:::

### 14. Scaled divs

:::{scale=0.6}
Ex eu aute incididunt, esse irure ut officia culpa adipiscing commodo
adipiscing, cupidatat dolor voluptate aliqua do dolore officia. Velit ullamco
culpa ea consectetur consequat, do aliqua cillum eu velit commodo. Est
adipiscing incididunt consectetur ad exercitation incididunt. Amet ea commodo
id duis veniam. Amet reprehenderit aute ipsum.
:::

:::{scale=1.0}
Nulla excepteur nisi dolor excepteur culpa reprehenderit sunt. Adipiscing
officia sed quis sunt labore enim, ipsum ullamco voluptate consequat lorem.
Lorem dolor aute anim culpa. Est laboris do esse pariatur. Id incididunt dolor
incididunt pariatur laboris voluptate, do labore veniam dolor ad lorem. Tempor
sint pariatur veniam. Do sint sed mollit eu ex velit qui. Do officia amet
officia id reprehenderit. Pariatur ad voluptate et.
:::

:::{scale=1.5}
Ipsum labore culpa et ad ex do labore. Cupidatat esse aliqua duis laboris ad
dolore voluptate, consequat velit ea ex. Est dolore ex eiusmod ut irure ad
amet. Quis labore magna incididunt laboris. Proident sit aliquip adipiscing
nisi amet minim, sit non sit eiusmod irure ipsum exercitation, dolor pariatur
laborum proident. Officia nostrud cillum aliquip et est consequat culpa, labore
aute anim eu magna nisi. Proident mollit culpa ullamco elit in lorem, cupidatat
fugiat ad irure labore ut occaecat, duis ad velit consectetur ipsum. Minim do
veniam ea nulla nostrud commodo aliquip, nostrud excepteur sunt consectetur,
consectetur id cillum occaecat sit.
:::
