:::{.chapter}
## Chapter 5: SPANs
### Test of many combinations of formating classes
:::

Lorem qui duis reprehenderit quis aliqua occaecat occaecat. Qui proident ullamco
aute adipiscing elit veniam tempor. Velit ut elit aute dolor deserunt sunt
ullamco, adipiscing veniam dolore deserunt duis ex pariatur nisi, consequat
aliquip consectetur esse velit anim laboris. Voluptate lorem sed mollit sint,
et amet esse commodo enim est veniam ex, velit deserunt do labore. Esse nostrud
qui minim dolore incididunt culpa. Aute sit reprehenderit magna.

### 1. Simple span

Here a sentence with [a span in the middle]{} and some normal text.

### 2. Basic formating

And the same thing with spans [this is bold]{.bold}, [this is italic]{.italic},
[this is strikethrough]{.strikethrough}, [this is in small caps]{.smallcaps},
[this is monospace]{.monospace}, [this is sans serif]{.sans} and
[this is all together]{.bold .italic .strikethrough .smallcaps}, that's it.

### 3. Scaling and offset

We can also scale the text bay any factor:

:::{.noparindent}
| [Jack be quick. (1)]{scale=0.5}
| [Jack be quick. (2)]{scale=0.8}
| [Jack be quick. (3)]{scale=1.0}
| [Jack be quick. (4)]{scale=1.2}
| [Jack be quick. (5)]{scale=1.5}
| [Jack be quick. (6)]{scale=2.5}
| [Jack be quick, JACK (7)]{scale=1.2}
:::

And with the horizontal and vertical offsets:

:::{.noparindent}
| Alpha [Beta]{scale=1.25} Gamma. (1)
| Alpha [Beta]{scale=1.25,8em,1.3\nbs} Gamma. (2)\par
:::

### 4. Horizontal space

You can also insert horizontal space before [**a span**]{hspace_before=2cm} or
eventually after [**a span**]{hspace_after=2cm} and even to both sides of
[**a span**]{hspace_both=2cm} just like that.

### 5. Phantom text

You can use phantom text, i.e. text that that won't show but leaves a
horizontal gap as if the text were there. For example here you can't see that
the words « [you can't see me, I'm a ghost]{.phantom} » are written, but they
are here ! The text was « you can't see me, I'm a ghost ».

### 6. Horizontal filling

You can also fill horizontal space in a line:

:::{.noparindent}
| start **no hfill** end
| start [**hfill only before**]{hfill=before} end
| start [**hfill only after**]{hfill=after} end
| start [**hfill on both side**]{hfill=both} end
:::
