:::{.chapter}
# Chapter 4: DIVs and SPANs
## Test of many combinations of formating classes
:::

{{< quickchapter "1. Simple div" >}}

:::{}
{{< lipsum 1 >}}

{{< lipsum 1 >}}

{{< lipsum 1 >}}
:::

{{< quickchapter "2. Bold div" >}}

Two next paragraphs are formated as bold.

:::{.bold}
{{< lipsum 1 >}}

{{< lipsum 1 >}}
:::

{{< quickchapter "3. Italic div" line=false >}}

Two next paragraphs are formated as italic.

:::{.italic}
{{< lipsum 1 >}}

{{< lipsum 1 >}}
:::

{{< quickchapter "4. Strikethrough div" line=true >}}

Two next paragraphs are formated as strikethrough.

:::{.strikethrough}
{{< lipsum 1 >}}

{{< lipsum 1 >}}
:::

{{< quickchapter "5. Small capitals div" >}}

Two next paragraphs are formated in small caps.

:::{.smallcaps}
{{< lipsum 1 >}}

{{< lipsum 1 >}}
:::

{{< quickchapter "6. Monospaced div" >}}

Five next paragraphs are formated in monospace (aka teletext) font.

:::{.monospace}
Unlike verbatim, you can use **bold text**, *italic text* and ***bold italic
text*** in the monospace divs or spans just like in any other place.

You can split a very log string so that it fits in the page via hyphenation by
inserting a `\-` where you want the string to be cut and wrapped. Here is an
example:

1111111111222222222233333333334444444444555555555566666\-6666677777777778888888888

{{< lipsum 1 >}}

{{< lipsum 1 >}}
:::

{{< quickchapter "7. Combined classes div" >}}

Two next paragraphs are formated with combinations of previous formating
classes.

:::{.bold .italic .strikethrough .smallcaps}
{{< lipsum 1 >}}

{{< lipsum 1 >}}
:::

{{< quickchapter "8. Div without paragraph indentation" >}}

Two next paragraphs have no paragraph indentation.

:::{.noparindent}
{{< lipsum 1 >}}

{{< lipsum 1 >}}
:::

{{< quickchapter "9. Div with space between paragraphs" >}}

Three next paragraphs space between them.

:::{parskip=1ex}
{{< lipsum 1 >}}

{{< lipsum 1 >}}

{{< lipsum 1 >}}
:::

And some text after the last paragraph (there should be space before it).

{{< clearpage >}}

{{< quickchapter "10. Vertival spaces" >}}

Next paragraph has filling space before and after and so should be vertically
centered.

:::{vfill=both}
{{< lipsum 1 >}}
:::

Some text down the page.

{{< clearpage >}}

Next paragraph has filling space before only and so should be pushed down the
page.

:::{vfill=before}
{{< lipsum 1 >}}
:::

Some text down the page.

{{< clearpage >}}

Next paragraph has filling space after only and so following content should be
pushed down the page.

:::{vfill=after}
{{< lipsum 1 >}}
:::

Some text down the page.

{{< clearpage >}}

Next div has vertical space before and after.

:::{vspace_both=3\nbs}
{{< lipsum 1 >}}

{{< lipsum 1 >}}
:::

Next div has vertical space before.

:::{vspace_before=3\nbs}
{{< lipsum 1 >}}

{{< lipsum 1 >}}
:::

Next div has vertical space after.

:::{vspace_after=3\nbs}
{{< lipsum 1 >}}

{{< lipsum 1 >}}
:::

Some text after.

{{< quickchapter "11. Margins" >}}

Next divs have different left margins.

:::{margin_left=1em}
{{< lipsum 1 >}}
:::

:::{margin_left=3em}
{{< lipsum 1 >}}
:::

:::{margin_left=5em}
{{< lipsum 1 >}}
:::

Next divs have different right margins.

:::{margin_right=1em}
{{< lipsum 1 >}}
:::

:::{margin_right=3em}
{{< lipsum 1 >}}
:::

:::{margin_right=5em}
{{< lipsum 1 >}}
:::

Next divs have different right and left margins.

:::{margin_both=1em}
{{< lipsum 1 >}}
:::

:::{margin_both=3em}
{{< lipsum 1 >}}
:::

:::{margin_both=5em}
{{< lipsum 1 >}}
:::

{{< quickchapter "11. Margins" >}}

Next divs have different left alignment.

:::{align=left}
{{< lipsum 1 >}}
:::

:::{align=right}
{{< lipsum 1 >}}
:::

:::{align=center}
{{< lipsum 1 >}}
:::

:::{align=justify}
{{< lipsum 1 >}}
:::

And you can nest them:

:::{align=left}
{{< lipsum 1 >}}

::::::{align=justify}
{{< lipsum 1 >}}
::::::

{{< lipsum 1 >}}
:::

{{< quickchapter "13. Scaled divs" >}}

:::{scale=0.6}
{{< lipsum 1 >}}
:::

:::{scale=1.0}
{{< lipsum 1 >}}
:::

:::{scale=1.5}
{{< lipsum 1 >}}
:::

{{< quickchapter "14. Span with formating" >}}

And the same thing with spans [this is bold]{.bold}, [this is italic]{.italic},
[this is strikethrough]{.strikethrough}, [this is in small caps]{.smallcaps},
[this is monospace]{.monospace} and
[this is all together]{.bold .italic .strikethrough .smallcaps}, that's it.

We can also scale the text bay any factor:

:::{.noparindent}
| [Jack be quick. (1)]{scale=0.5}
| [Jack be quick. (2)]{scale=0.8}
| [Jack be quick. (3)]{scale=1.0}
| [Jack be quick. (4)]{scale=1.2}
| [Jack be quick. (5)]{scale=1.5}
| [Jack be quick. (6)]{scale=2.5}
| [Jack be quick, JACK (7)]{scale=1.2}
:::

And with the horizontal and vertical offsets:

:::{.noparindent}
| Alpha [Beta]{scale=1.25} Gamma. (1)
| Alpha [Beta]{scale=1.25,8em,1.3\nbs} Gamma. (2)\par
:::

You can also insert horizontal space before [**a span**]{hspace_before=2cm} or
eventually after [**a span**]{hspace_after=2cm} and even to both sides of
[**a span**]{hspace_both=2cm} just like that.

Ypou can use phantom text, i.e. text that that won't show but leaves a
horizontal gap as if the text were there. For example here you can't see that
the words « [you can't see me, I'm a ghost]{.phantom} » are written, but they
are here ! The text was « you can't see me, I'm a ghost ».
