## Chapter 6: Header and footer {.nofldeco}

This chapter should not have a decoration for the first line.

The current part is {{< thepart >}}, the current chapter is {{< thechapter >}}
and the current quick chapter {{< thequickchapter >}}. This is the book
**{{< thetitle >}}** written by _{{< theauthor >}}_.

### A little quick chapter

The current page is {{< thepage >}}, the current chapter is {{< thechapter >}}
and the current quick chapter is {{< thequickchapter >}}.

Magna labore ullamco aliqua eiusmod amet sed ipsum. Irure cillum reprehenderit
consectetur. Non est occaecat amet labore, nisi aliquip amet magna enim
pariatur. Mollit voluptate veniam laborum proident, ut in laborum consequat
fugiat lorem non occaecat. Reprehenderit exercitation in occaecat commodo
ullamco. Eiusmod cupidatat exercitation eiusmod sed.

### Another quick chapter

The current page is {{< thepage >}}, the current chapter is {{< thechapter >}}
and the current quick chapter is {{< thequickchapter >}}.

Esse eu officia sit laborum magna ut, sunt culpa aliquip labore in officia.
Reprehenderit do sed duis est. Nulla sed tempor sed velit. Tempor eu esse
occaecat anim quis sed. Officia cillum labore minim ullamco ea laboris ea,
cillum aute proident occaecat sit consectetur nulla reprehenderit, dolor do ea
qui. Ipsum sed enim aliquip laboris laborum ex. Reprehenderit voluptate
consectetur reprehenderit dolore, non sunt amet ad nostrud occaecat. In eu ut
ex irure anim est nisi. Sunt in incididunt nostrud.

### Changing the header/footer style

We will now test the different kind of header and footer style one by one on
dedicated pages.

{{< clearpage nextpagestyle=fancy >}}

:::{vfill=both scale=3 align=center}
Page with a **fancy** style
:::

{{< clearpage nextpagestyle=empty >}}

:::{vfill=both scale=3 align=center}
Page with a **empty** style
:::

{{< clearpage nextpagestyle=footer >}}

:::{vfill=both scale=3 align=center}
Page with a **footer** style
:::

{{< clearpage nextpagestyle=forcenumber >}}

:::{vfill=both scale=3 align=center}
Page with a **forcenumber** style
:::

{{< clearpage nextpagestyle=dropfoliobeneath >}}

:::{vfill=both scale=3 align=center}
Page with a **dropfoliobeneath** style
:::

{{< clearpage nextpagestyle=dropfolioinside >}}

:::{vfill=both scale=3 align=center scale=3 align=center}
Page with a **dropfolioinside** style
:::

### Changing the header content

On the next page we change the header content for recto and verso.

{{< clearpage >}}

[New *verso* header]{.setheaderverso}
[New **recto** header]{.setheaderrecto}

:::{vfill=both scale=3 align=center}
Page with has a **custom verso header**.
:::

{{< clearpage >}}

:::{vfill=both scale=3 align=center}
Page with has a **custom recto header**.
:::
