:::{.chapter}
## Chapter 3: Basic **formating**
### Where we are going to present all the [basic]{scale=0.5} feature

Some few stuffs in the chapter header.

Some **other** stuffs in the chapter header.
:::

Ut commodo in adipiscing commodo minim occaecat culpa. Qui adipiscing dolor
nulla id excepteur est. Nisi nostrud laboris eu aute eu minim, dolore ea ad
lorem. Mollit ipsum et ad enim commodo consectetur sint. Sunt aute consequat
mollit pariatur adipiscing reprehenderit. Sint quis minim elit, excepteur
voluptate sit proident. Sed eu consectetur anim sint sunt aute, nulla laborum
aliqua cupidatat exercitation fugiat. Sit deserunt laborum enim non, sit
excepteur nostrud do et, labore mollit consectetur et. Sed nostrud laborum
culpa non. Aliquip est nisi fugiat laboris sed amet laborum, laborum proident
non anim id dolore nisi.

### 1. Inline formatting [this is provided by pandoc]{scale=0.5}

You can use *italics*, **bold**, ***bold italics***, super^script^,
sub~script~, ~~strikethrough~~, `verbatim inline code`, Angle brackets links
<https://quarto.org>, Classic markdown links [Quarto](https://quarto.org).

### 2. Symbols and unicode

You can use special characters:

:::{.noparindent}
| hyphen (inter-word) -
| en dash --
| em dash ---
| ellipsis ...
| simple quotes '...'
| double quotes "..."
| french quotes «...»
| dollar sign $
| pound sign £
| euro sign €
| hashtag #
| pipe |
| star sign *
| slash /
| backslash \
:::

### 3. Footnotes

Footnotes with multiple paragraphs can't be used on the first line of a chapter
or quick chapter whose first line is marked to highlight the beginning of that
chapter or quickchapter.

You can also have footnote reference,[^1] and another.[^longnote]. Here is an
inline note.^[Inlines notes are easier to write, since you don't have to pick an
identifier and move down to
type the note.]

[^1]: Here is the footnote.

[^longnote]: Here's one with multiple blocks.

    Subsequent paragraphs are indented to show that they
belong to the previous footnote.

    The whole paragraph can be indented, or just the first
    line.  In this way, multi-paragraph footnotes work like
    multi-paragraph list items.

This paragraph won't be part of the note, because it
isn't indented.

### 4. Basic math integration

You can also use so basic math like $E = mc^2$ or even present them as
equations:

$$
f(a)={\frac {1}{2\pi i}}\oint _{\gamma }{\frac {f(z)}{z-a}}\,dz
\tag{1}
$$

### 5. Inline blocks

And we have support for line blocks too :

| This is a line block
| With multiple lines of text that should respect both word wrap...
|
| ...And manual linebreaks
| Like this

But if you want them without indentation at each new paragraph, you need to put
it a div block with the `.noparindent` class. Just like that:

:::{.noparindent}
| This is another line block
| With multiple lines of text that should respect both word wrap...
|
| ...And manual linebreaks
| Like this.
|
| But this time we have no paragraph indent.
:::

There is no support for code blocks (they are very complex and not something you
expect to need in a fiction novel) but you can use line blocks with
`noparindent` and `.monospace` classes applied:

:::{.noparindent .monospace}
| This is yet another line block (that mimicks a code block)
| With multiple lines of text that should respect both word wrap...
|
| ...And manual linebreaks
| Like this.
|
| But this time we have no paragraph indent and this should be in monospace font.
:::

And some more text after.

### 6. Scene breaks

Here are some `scenebreak` via headings level 4 (with convenient names) of
different types:

Do officia deserunt aute. Eu incididunt nostrud ex occaecat. Deserunt sunt
nostrud in sunt. Incididunt nisi eu voluptate proident. Anim eu tempor commodo.
Aliquip elit et culpa, excepteur magna officia qui pariatur ullamco laboris.
Duis enim reprehenderit adipiscing proident ea consectetur, laboris
reprehenderit aliqua et occaecat. Magna irure amet sit deserunt. Dolore eiusmod
do labore deserunt mollit nostrud magna. Magna incididunt ea magna.

#### Scene break

Aute et nisi anim aliquip do commodo ea, ut enim lorem duis in. Dolore dolore
laborum cupidatat deserunt. Amet pariatur cillum quis sint ipsum commodo non.
Eiusmod aliqua cillum adipiscing ad tempor amet in. Commodo aute occaecat
eiusmod est cillum dolore proident, nisi enim nisi ut cillum, nulla ipsum
excepteur sint elit tempor mollit. Deserunt eu sit sunt reprehenderit ut fugiat
officia, magna laborum ut enim aute cillum. Minim dolore qui non anim cupidatat
id deserunt. Nulla aute et consequat exercitation esse cupidatat voluptate,
minim cillum in incididunt aliquip labore exercitation laborum, veniam aliquip
incididunt aliqua labore fugiat veniam irure. Pariatur velit dolore adipiscing.
Qui eu enim pariatur esse in esse proident.

#### Scene break blank

Incididunt aliquip excepteur fugiat aliqua non. Adipiscing voluptate in esse
adipiscing. Reprehenderit magna proident lorem minim. Consequat cillum
cupidatat occaecat deserunt ut consequat nisi. Velit fugiat non consequat amet,
quis ea aute ad commodo et occaecat. Sint eiusmod deserunt velit.

#### Scene break line

Non nulla occaecat commodo excepteur, fugiat eu in eiusmod. Sint aute adipiscing
laboris irure dolor nostrud occaecat, quis aliqua in ut ea adipiscing. Laborum
ipsum minim eiusmod ad. Veniam labore eu do, cillum exercitation anim non nisi.
Adipiscing aliquip ut non nostrud amet, reprehenderit reprehenderit veniam amet
cupidatat commodo duis. Laborum officia anim ea enim. Sunt labore nostrud magna
sed. Voluptate velit in reprehenderit labore. Exercitation esse deserunt
voluptate pariatur quis.

#### Scene break stars

Adipiscing sed ut esse magna ut eiusmod, qui dolor mollit dolor dolor voluptate
consectetur id. Excepteur ut consequat eiusmod, nulla pariatur nostrud elit
incididunt. Eiusmod adipiscing sed aliquip commodo aute duis. Nulla ipsum
tempor excepteur. Occaecat et eu quis, nisi occaecat aute incididunt anim
laboris. Eiusmod ullamco ut do. Dolor sit eiusmod laborum ipsum est, id nisi ad
magna consequat. Veniam nostrud elit eiusmod sed ipsum ut occaecat. Qui magna
do elit. Minim anim do culpa duis ea deserunt sunt.

### 7. Spaces

Now we jump 5 lines with `emptylines` shortcode.

{{< emptylines 5 >}}

We can also fill a vertical space with as much empty line as possible (pushing
following content down) using `vfill` shortcode:

{{< vfill >}}

And this is pushed at the end of the page.

{{< clearpage >}}

### 8. Epigraphs

You can use an epigraph with an `epigraph` div:

:::{.epigraph by="John Lennon" from="An interview"}
When I was 5 years old, my mother always told me that happiness was the key
to life. When I went to school, they asked me what I wanted to be when I
grew up. I wrote down ‘happy’. They told me I didn’t understand the
assignment, and I told them they didn’t understand life.
:::

You can even use an epigraph with multiple paragraphs:

:::{.epigraph by="John Lennon" from="An interview"}
When I was 5 years old, my mother always told me that happiness was the key
to life. When I went to school, they asked me what I wanted to be when I
grew up. I wrote down ‘happy’. They told me I didn’t understand the
assignment, and I told them they didn’t understand life.

When I was 5 years old, my mother always told me that happiness was the key
to life. When I went to school, they asked me what I wanted to be when I
grew up. I wrote down ‘happy’. They told me I didn’t understand the
assignment, and I told them they didn’t understand life.
:::

...or with line block:

:::{.epigraph by="Robert Frost" from="Nothing Gold Can Stay"}
| Nature's first green is gold,
| Her hardest hue to hold.
| Her early leaf's a flower;
| But only so an hour.
:::

### 9. Page breaks

It's possible to ask for a new page with the `clearpage` shortcode:

{{< clearpage >}}

This should appear on a new page.

And you can even ask for for a new page  that force the next page to be recto with the `cleartorecto` shortcode:

{{< cleartorecto >}}

This should appear on a new recto page.

And you can also simply put an empty page using `emptypage` and `clearpage` shortcode:

{{< clearpage >}}
{{< emptypage >}}
{{< clearpage >}}

And here is the followup after an empty page.

### 10. Colors

You can specify the color of the text (the last one is white but you can't see
it on white background):

:::{.noparindent}
| [this text is in color **black** and it's *beautiful*]{color=black}
| [this text is in color **gray1** and it's *beautiful*]{color=gray1}
| [this text is in color **gray2** and it's *beautiful*]{color=gray2}
| [this text is in color **gray3** and it's *beautiful*]{color=gray3}
| [this text is in color **gray4** and it's *beautiful*]{color=gray4}
| [this text is in color **gray5** and it's *beautiful*]{color=gray5}
| [this text is in color **gray6** and it's *beautiful*]{color=gray6}
| [this text is in color **gray7** and it's *beautiful*]{color=gray7}
| [this text is in color **gray8** and it's *beautiful*]{color=gray8}
| [this text is in color **gray9** and it's *beautiful*]{color=gray9}
| [this text is in color **white** and it's *beautiful*]{color=white} (white)
:::
