## Half Title page

{{< emptylines 6 >}}

```{=latex}
{\booktitlefont
```

:::{align=right}
<!-- TODO: Use first_words=??? and last_words=??? attributes here on title -->
[**Live Long and**]{scale=1.8}
{{< emptylines 1 >}}
[**Die Hard**]{scale=2.4 color=gray5}
:::
```{=latex}
}
```

## Blank page

{{< emptypage >}}

## Full Title page

:::{align=center vspace_before=5\nbs}

<!-- TODO: Use first_words=??? and last_words=??? attributes here on title -->
```{=latex}
{\booktitlefont
```

[**Live Long and**]{scale=3.6}
{{< emptylines 2 >}}
[**Die Hard**]{scale=4.8 color=gray5}

```{=latex}
}
```

{{< emptylines 1.5 >}}

[ {{< meta subtitle>}} ]{scale=1.6}

{{< emptylines 4 >}}

```{=latex}
\ChapterDeco[6]{\decoglyph{n9548}}
```

{{< emptylines 4 >}}

[ {{< meta author>}} ]{scale=3}

{{< vfill >}}

::::::{scale=1.25}
| {{< meta publisher.name>}}
| {{< meta publisher.location>}}
::::::

:::


## Legal notice

:::{align=center .italic}

::::::{.smallcaps vfill=before}
{{< meta title >}}
::::::

<!-- Can be copyrights, copyleft, licence... -->
Copyright ©2024 {{< meta author >}}.

All Rights Reserved.

<!-- Or similar language boiler plate) -->
::::::{vspace_both=1\nbs}
| This is a work of fiction.
| All persons and events are
| from the author's imagination.
| Resemblance to any real person,
| living or dead, is coincidental.
::::::

<!-- Whatever it is. No barcode, just number. -->
ISBN {{< meta isbn >}}

::::::{vspace_both=1\nbs}
| {{< meta publisher.name >}},
| {{< meta publisher.location >}}
| {{< meta publisher.online_contact >}}
::::::

<!-- Fiction often does not need catalog data. -->
| Publisher's Cataloging-In-Publication Data
| available upon request.
:::

## Epigraph

<!--
Note that since epigraphs are ornamental in nature, they are usually not
considered fair use. Publishers often require writers to seek permission
to quote material for epigraphs, especially lyrics and modern poetry.
See: https://style.mla.org/styling-epigraphs/
-->
:::{.epigraph from="Prophecy of Claudius" by="Claudius" lines_before=7}
| When the lone raccoon howls at dusk,
| And white birds cease their twitter,
| Then shall the rivers overflow with mead.
:::

## Foreword {.chapterlike}

Sit commodo incididunt nulla. Quis veniam reprehenderit excepteur proident
commodo non. Et eu tempor labore sunt nulla enim. Ea proident ex cillum, sit
cillum fugiat fugiat do. Quis ullamco aliqua enim. Excepteur dolore aliqua non
nostrud sed tempor. Commodo amet consectetur consequat laborum. Ipsum et irure
laborum aute.

Laborum sed in sint eu commodo do duis, aute proident eiusmod ad proident ut
aute laborum. Minim deserunt id cillum officia, officia lorem sunt qui elit
aliqua, qui veniam labore occaecat excepteur sint ullamco excepteur. Ullamco
tempor aliqua labore. Qui et ea ad et deserunt, magna labore sit do
exercitation aliqua, sint lorem consectetur aute duis. Sint cillum consectetur
labore non eiusmod incididunt consectetur, mollit tempor nisi labore. Magna
anim ullamco ex magna, voluptate laborum officia exercitation aliquip
incididunt tempor culpa, ut aute irure amet do sunt. Adipiscing qui aute velit
ex elit nulla. Anim excepteur adipiscing velit, ea anim fugiat laboris fugiat
ex cupidatat.

Aute consectetur quis irure duis enim. Occaecat anim commodo sit quis id
nostrud. Magna in fugiat ipsum lorem in, in magna eu ex pariatur. Sunt fugiat
laboris quis minim minim mollit ut, magna irure officia pariatur in duis
fugiat, dolore nostrud sed reprehenderit labore sit ipsum. Ipsum reprehenderit
id officia ipsum dolore. Ex adipiscing in mollit. Cupidatat nisi ut sed do ea,
nisi veniam ex et. Ea qui officia sint ad deserunt. Commodo sunt et laborum
irure non. Tempor et tempor aliqua nostrud officia duis lorem, tempor proident
ad enim irure reprehenderit, laborum mollit elit consectetur.

Lorem pariatur aute sint qui. Occaecat pariatur aute laboris. Dolor sint non
consequat. Ut minim mollit quis sunt et est labore. Est pariatur velit ea quis
adipiscing eu. Nulla reprehenderit dolor do consectetur. Cillum aliquip sed
non.

Voluptate laboris elit officia. Deserunt consectetur minim reprehenderit,
adipiscing lorem id ut. Aute cupidatat exercitation veniam et aliquip magna.
Excepteur cupidatat nulla reprehenderit qui ad, non laboris eu aliquip culpa,
anim reprehenderit reprehenderit mollit quis proident. Culpa tempor proident
occaecat, consectetur id nostrud velit ad velit ad fugiat.

{{< cleartorecto >}}

## Table of content {.chapterlike}

:::{.tableof}
[Foreword]{.toc_part page=vi}
[First part]{.toc_part page=1}
[Chapter One [with default placement]{scale=0.8}]{.toc_chap number=1 page=2}
[Chapter Two [with more space before title]{scale=0.8}]{.toc_chap number=2 page=5}
[Second part]{.toc_part page=9}
[Chapter 3: Basic]{.toc_chap number=3 page=10}
[Chapter 4: DIVs]{.toc_chap number=4 page=22}
[Chapter 5: SPANs]{.toc_chap number=5 page=40}
[Chapter 6: Header and footer]{.toc_chap number=6 page=42}
[_Take your breath this is log chapters_]{.toc_blank page=44}
[Chapter 7: Chapter first line decoration]{.toc_chap number=7 page=50}
[Chapter 8: Unicode and 😁emojis🙃]{.toc_chap number=8 page=54}
[Afterword]{.toc_part page=162}
:::
